# Generated by Django 3.2.12 on 2022-03-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketOnlineDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('device_id', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('registered_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_active_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
