# Generated by Django 3.2.12 on 2022-03-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api_gateway_websocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websocketonlinedevice',
            options={'verbose_name': 'WebSocket在线客户设备', 'verbose_name_plural': 'WebSocket在线客户设备'},
        ),
    ]
